version: '3.7'

services:
  victoriametrics_ubuntu:
    image: geircode/victoriametrics_ubuntu:latest
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: victoriametrics_ubuntu-1
    ports:
      - 8428:8428
      - 2003:2003
      - 4242:4242
    environment:
      - storageDataPath=/storage
      - graphiteListenAddr=:2004
      - opentsdbListenAddr=:4243
      - httpListenAddr=:8429
    volumes:
      - vmdata:/storage
    command:
      - '-envflag.enable'    
    networks:
      - learning-victoriametrics_network
networks:
  learning-victoriametrics_network:
    name: learning-victoriametrics_network
    external: true
volumes:
  vmdata: {}